create table if not exists public.health_checks (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default now(),
  source text not null default 'github-actions' check (
    length(trim(source)) between 1 and 80
  )
);

comment on table public.health_checks is
  'Minimal backend availability check state. This is operational monitoring, not artificial user activity.';
comment on column public.health_checks.checked_at is
  'Last time the backend health check confirmed Supabase could be reached.';
comment on column public.health_checks.source is
  'Backend scheduler that performed the check, for example github-actions.';

alter table public.health_checks enable row level security;

insert into public.health_checks (id, checked_at, source)
values (1, now(), 'github-actions')
on conflict (id) do nothing;

drop policy if exists "backend health check reads single row" on public.health_checks;
create policy "backend health check reads single row"
on public.health_checks
for select
to service_role
using (id = 1);

drop policy if exists "backend health check updates single row" on public.health_checks;
create policy "backend health check updates single row"
on public.health_checks
for update
to service_role
using (id = 1)
with check (id = 1);

revoke all on public.health_checks from anon, authenticated;

grant usage on schema public to service_role;
grant select, update on public.health_checks to service_role;
